# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
          url: jdbc:mysql://127.0.0.1:3306/blog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
          username: root
          password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
logging:
   level:
     root: info
     com.mehow: debug
   file:
    name: log/blog.log
server:
  port: 80
  #ssl:
    #protocol: TLS
    #key-store: classpath:adheres.jks
    #key-password: k9cid494x7j2o6
    #key-store-type: JKS